### ISSUE TITLE
发生未知错误 怎么解决？

### ISSUE THREAD

**Issue by David-Liv** [idranme/koishi-plugin-fish-speech-online#5] opened 2024-07-04 17:13 UTC
![CC20939275C45198BE6A9ECAF069EA4C](https://github.com/idranme/koishi-plugin-fish-speech-online/assets/139309528/b8435f31-5639-41ee-8b0a-590d6c3f8e1e)

**Comment by idranme** [comment] 2024-07-12 16:37
Duplicate of #4

**Closed as completed by idranme** 2024-07-12 16:37 UTC
